# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for DatingApp
  pod "FBSDKCoreKit";
  pod "FBSDKLoginKit";
  pod "FBSDKShareKit";
  target 'DatingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DatingApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DatingApp-tvOS


end